### ISSUE TITLE
Allow POST

### ISSUE THREAD

**Issue by ElektroStudios** [tiansh/classical-search-bar#1]
Could you please allow POST requests to be entered and be functional, like for example in this format?:

`data:text/html,<body onload="document.body.firstChild.submit()"><form method="post" action="http://tumejortorrent.com/buscar"><input name="ordenar" value="Nombre"><input name="inon" value="Ascendente"><input name="q" value="{searchTerms}">`

When entering that code in the navigation address bar all works fine, but when entering it inside the "Search URL" field of your extension the seach engine is not functional...

Any solution for this, please?.

**Comment by tiansh** [comment]
Firefox with web extension only allows one search provider been registered by an extension, and the search url could not be changed after extension installation. As a result, this extension registered a fake url, and try to redirect it to the url user chosen. As it’s http redirect (through locally), it can only redirect to http/https urls (not data: one). I’ve no idea how to redirect it to act a post submission.

**Comment by tiansh** [comment]
For your use case, I would suggest serve that page on an http server so that it can be handled by this extension... as long as you don’t care the terrible performance...

**Comment by ElektroStudios** [comment]
Don't worry, if its not possible in a friendly way then its not possible. Thanks for your support and time!

**Comment by tiansh** [comment]
I just came up with an idea that make the page your data uri described as a built in page in extension. And redirect it to that page. I'm not sure if it works. I will have a try, maybe a few days later.

But I still don't know how to make the user interface of options page. I would believe most users don't familiar with what HTTP methods mean, and what POST is. As a result, adding another input field for `search_url_post_params` on the options page would just make them confused since they do not need this function and cannot understand it.

btw, would you mind posting the feature request as another issue?

**Comment by ElektroStudios** [comment]
of course don't worry! i'll do it

**Comment by tiansh** [comment]
Added in version 1.3.0 as a hidden feature.
Follow [this guide](https://github.com/tiansh/classical-search-bar/wiki/Config-POST-Search-Providers) to add your search providers.
You could Import (and append) [this file](https://github.com/tiansh/classical-search-bar/files/2173815/tumejortorrect.txt) for your exampled search provider.
