### ISSUE TITLE
Highlight current search provider in list

### ISSUE THREAD

**Issue by ElektroStudios** [tiansh/classical-search-bar#3]
When opening/displaying the search provider list, it would be a great hint for our eyes if the current selected provider appears with the background highlighted in any color, like for example:

![](https://i.imgur.com/vB3KxJU.png)

Thanks for read.

**Comment by tiansh** [comment]
Maybe make the current one selected by default (with the gray background currently used)?
<img width="209" alt="selected-search-engine" src="https://user-images.githubusercontent.com/6500326/42355418-66682982-8110-11e8-82a1-6f43c6e954e2.png">

Or a tick mark before it? (A tick mark may be strange since we already had an icon.)
<img width="213" alt="tick-mark-in-menu" src="https://user-images.githubusercontent.com/6500326/42355435-7082edda-8110-11e8-8e78-21df8895b215.png">

**Comment by ElektroStudios** [comment]
"Maybe make the current one selected by default (with the gray background currently used)"

Yes that is was I tried to express in my request, to make it selected / highlighted.

However a tick mark would be a great solution too!.

**Comment by tiansh** [comment]
Made the current one selected when pop up shown in version 1.3.0
